### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [joshpetras/bwa-u4-feature-request#4]
Grade: **Meets Expectations**

This feature request is great! I think the background explained the idea well, and also gave good reasoning for why it should be implemented. The technical design explains everything that is required to get this up and running which also indicates how simple the implementation would be. The caveat section was excellent as well - you pointed out a potential drawback and a potential solution to that drawback which is typically what we want to see. Next steps, I would attempt to implement this feature request into your project to see if it was more challenging or less challenging than you thought it would be.

**Comment by joshpetras** [comment]
Thanks. The feature has been implemented per the feature request specifications and works great.
